DELIMITER //

CREATE EVENT IF NOT EXISTS CleanUpOldClassSessions
ON SCHEDULE EVERY 1 MONTH
STARTS (TIMESTAMP(CURRENT_DATE) + INTERVAL 1 MONTH)
DO
    DELETE FROM ClassSession
    WHERE EndTime < NOW() - INTERVAL 1 MONTH;

//

DELIMITER ;
